// Generated by CoffeeScript 1.6.3
(function() {
  var Gitlab, assert, credentials, gitlab;

  assert = require('assert');

  Gitlab = require('..').ApiV3;

  credentials = {
    host: "http://demo.gitlab.com",
    token: "Wvjy2Krpb7y8xi93owUz",
    password: "123456",
    login: "test@test.com"
  };

  gitlab = new Gitlab({
    token: credentials.token,
    url: credentials.host
  });

  describe('User', function() {
    describe('#all()', function() {
      return it('should retrieve array of users without error', function(done) {
        return gitlab.users.all(function(result) {
          done();
          return result;
        });
      });
    });
    return describe('#login()', function() {
      return it('should retrieve a users session without error', function(done) {
        return gitlab.users.session(credentials.login, credentials.password, function(result) {
          done();
          return result;
        });
      });
    });
  });

  describe('Project', function() {
    return describe('#all()', function() {
      return it('should retrieve array of projects without error', function(done) {
        return gitlab.projects.all(function(result) {
          done();
          return result;
        });
      });
    });
  });

}).call(this);
