// Generated by CoffeeScript 1.4.0
(function() {
  var BaseModel,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  BaseModel = (function() {

    function BaseModel(client) {
      this.client = client;
      this._init = __bind(this._init, this);

      this.load = __bind(this.load, this);

      this._init();
    }

    BaseModel.prototype.load = function(model) {
      return require("./" + model)(this.client);
    };

    BaseModel.prototype._init = function() {
      this.debug = this.client.debug;
      this.get = this.client.get;
      this.post = this.client.post;
      this.put = this.client.put;
      this["delete"] = this.client["delete"];
      if (this.init != null) {
        return this.init();
      }
    };

    return BaseModel;

  })();

  module.exports = BaseModel;

}).call(this);
