// Generated by CoffeeScript 1.6.3
(function() {
  var BaseModel, Groups, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseModel = require('../BaseModel');

  Groups = (function(_super) {
    __extends(Groups, _super);

    function Groups() {
      this.listProjects = __bind(this.listProjects, this);
      this.show = __bind(this.show, this);
      this.all = __bind(this.all, this);
      _ref = Groups.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Groups.prototype.all = function(params, fn) {
      var _this = this;
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      if ('function' === typeof params) {
        fn = params;
        params = {};
      }
      this.debug("Groups::all()");
      if (params.per_page == null) {
        params.per_page = 100;
      }
      return this.get("groups", params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };

    Groups.prototype.show = function(groupId, fn) {
      var _this = this;
      if (fn == null) {
        fn = null;
      }
      this.debug("Groups::show()");
      return this.get("groups/" + (parseInt(groupId)), function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };

    Groups.prototype.listProjects = function(groupId, fn) {
      var _this = this;
      if (fn == null) {
        fn = null;
      }
      this.debug("Groups::listProjects()");
      return this.get("groups/" + (parseInt(groupId)), function(data) {
        if (fn) {
          return fn(data.projects);
        }
      });
    };

    return Groups;

  })(BaseModel);

  module.exports = function(client) {
    return new Groups(client);
  };

}).call(this);
