// Generated by CoffeeScript 1.6.3
(function() {
  var BaseModel, ProjectHooks, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseModel = require('../BaseModel');

  ProjectHooks = (function(_super) {
    __extends(ProjectHooks, _super);

    function ProjectHooks() {
      this.remove = __bind(this.remove, this);
      this.update = __bind(this.update, this);
      this.add = __bind(this.add, this);
      this.show = __bind(this.show, this);
      this.list = __bind(this.list, this);
      _ref = ProjectHooks.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    ProjectHooks.prototype.list = function(projectId, fn) {
      var _this = this;
      if (fn == null) {
        fn = null;
      }
      this.debug("Projects::hooks()");
      return this.get("projects/" + (parseInt(projectId)) + "/hooks", function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };

    ProjectHooks.prototype.show = function(projectId, hookId, fn) {
      var _this = this;
      if (fn == null) {
        fn = null;
      }
      this.debug("Projects::hook()");
      return this.get("projects/" + (parseInt(projectId)) + "/hooks/" + (parseInt(hookId)), function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };

    ProjectHooks.prototype.add = function(projectId, url, fn) {
      var params,
        _this = this;
      if (fn == null) {
        fn = null;
      }
      this.debug("Projects::addHook()");
      params = {
        url: url
      };
      return this.post("projects/" + (parseInt(projectId)) + "/hooks", params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };

    ProjectHooks.prototype.update = function(projectId, hookId, url, fn) {
      var params,
        _this = this;
      if (fn == null) {
        fn = null;
      }
      this.debug("Projects::saveHook()");
      params = {
        access_level: parseInt(accessLevel)
      };
      return this.put("projects/" + (parseInt(projectId)) + "/hooks/" + (parseInt(hookId)), params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };

    ProjectHooks.prototype.remove = function(projectId, hookId, fn) {
      var _this = this;
      if (fn == null) {
        fn = null;
      }
      this.debug("Projects::removeHook()");
      return this["delete"]("projects/" + (parseInt(projectId)) + "/hooks/" + (parseInt(hookId)), function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };

    return ProjectHooks;

  })(BaseModel);

  module.exports = function(client) {
    return new ProjectHooks(client);
  };

}).call(this);
