// Generated by CoffeeScript 1.7.1
(function() {
  var BaseModel, ProjectIssues, Utils,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseModel = require('../BaseModel');

  Utils = require('../Utils');

  ProjectIssues = (function(_super) {
    __extends(ProjectIssues, _super);

    function ProjectIssues() {
      this.getOne = __bind(this.getOne, this);
      this.list = __bind(this.list, this);
      return ProjectIssues.__super__.constructor.apply(this, arguments);
    }

    ProjectIssues.prototype.list = function(projectId, params, fn) {
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("ProjectIssues::issues()");
      if ('function' === typeof params) {
        fn = params;
        params = {};
      }
      if (params.page == null) {
        params.page = 1;
      }
      if (params.per_page == null) {
        params.per_page = 100;
      }
      return (function() {
        var cb, data;
        data = [];
        cb = (function(_this) {
          return function(err, retData) {
            if (err) {
              if (fn) {
                return fn(data);
              }
            }
            if (retData.length === params.per_page) {
              _this.debug("Recurse ProjectIssues::list()");
              data = data.concat(retData);
              params.page++;
              return _this.get("projects/" + (Utils.parseProjectId(projectId)) + "/issues", params, cb);
            } else {
              data = data.concat(retData);
              if (fn) {
                return fn(data);
              }
            }
          };
        })(this);
        return this.get("projects/" + (Utils.parseProjectId(projectId)) + "/issues", params, cb);
      }).bind(this)();
    };

    ProjectIssues.prototype.getOne = function(projectId, issueId, params, fn) {
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("ProjectIssues::getOne()");
      if (projectId.toString().indexOf("/") !== -1) {
        projectId = encodeURIComponent(projectId);
      } else {
        projectId = parseInt(projectId);
      }
      if (issueId.toString().indexOf("/") !== -1) {
        issueId = encodeURIComponent(issueId);
      } else {
        issueId = parseInt(issueId);
      }
      return this.get("projects/" + projectId + "/issues/" + issueId, params, function(data) {
        if (fn) {
          return fn(data);
        }
      });
    };

    return ProjectIssues;

  })(BaseModel);

  module.exports = function(client) {
    return new ProjectIssues(client);
  };

}).call(this);
