// Generated by CoffeeScript 1.6.3
(function() {
  var BaseModel, ProjectIssues, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseModel = require('../BaseModel');

  ProjectIssues = (function(_super) {
    __extends(ProjectIssues, _super);

    function ProjectIssues() {
      this.list = __bind(this.list, this);
      _ref = ProjectIssues.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    ProjectIssues.prototype.list = function(projectId, params, fn) {
      if (params == null) {
        params = {};
      }
      if (fn == null) {
        fn = null;
      }
      this.debug("ProjectIssues::issues()");
      if ('function' === typeof params) {
        fn = params;
        params = {};
      }
      if (params.page == null) {
        params.page = 1;
      }
      if (params.per_page == null) {
        params.per_page = 100;
      }
      return (function() {
        var cb, data,
          _this = this;
        data = [];
        cb = function(retData) {
          if (retData.length === 100) {
            _this.debug("Recurse ProjectIssues::all()");
            data = data.concat(retData);
            params.page++;
            return _this.all(params, cb);
          } else {
            data = data.concat(retData);
            if (fn) {
              return fn(data);
            }
          }
        };
        return this.get("projects/" + (parseInt(projectId)) + "/issues", params, cb);
      }).bind(this)();
    };

    return ProjectIssues;

  })(BaseModel);

  module.exports = function(client) {
    return new ProjectIssues(client);
  };

}).call(this);
