// Generated by CoffeeScript 1.7.1
(function() {
  var ApiBaseHTTP, debug,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  debug = require('debug')('gitlab:ApiV2');

  ApiBaseHTTP = require('./ApiBaseHTTP').ApiBaseHTTP;

  module.exports.ApiV2 = (function(_super) {
    __extends(ApiV2, _super);

    function ApiV2() {
      this.handleOptions = __bind(this.handleOptions, this);
      return ApiV2.__super__.constructor.apply(this, arguments);
    }

    ApiV2.prototype.handleOptions = function() {
      console.warn('ApiV2 is deprecated');
      ApiV2.__super__.handleOptions.apply(this, arguments);
      this.options.base_url = 'api/v2';
      return debug("handleOptions()");
    };

    return ApiV2;

  })(ApiBaseHTTP);

}).call(this);
