// Generated by CoffeeScript 1.7.1
(function() {
  var ApiV2, ApiV3;

  ApiV2 = require('./ApiV2').ApiV2;

  ApiV3 = require('./ApiV3').ApiV3;

  module.exports = ApiV3;

  module.exports.ApiV2 = ApiV2;

  module.exports.ApiV3 = ApiV3;

}).call(this);
