// Generated by CoffeeScript 1.7.1
(function() {
  var ApiV3;

  ApiV3 = require('./ApiV3').ApiV3;

  module.exports = function(options) {
    return new module.exports.ApiV3(options);
  };

}).call(this);
